language: c
sudo: true
cache: ccache
dist: bionic
compiler: gcc
script:
  #- sudo apt install bc build-essential flex bison libssl-dev libelf-dev qt5-default pkg-config libncurses-dev -y
  - git clone https://github.com/microsoft/WSL2-Linux-Kernel.git -b linux-msft-wsl-4.19.y
  - cd WSL2-Linux-Kernel
  - curl https://raw.githubusercontent.com/Bartixxx32/WSL2-kernel-modified/master/kernel-config >> .config
  - make CC="ccache gcc" -j2
  
