# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Clone
      run: git clone https://github.com/microsoft/WSL2-Linux-Kernel.git -b linux-msft-wsl-4.19.y
    - name: Requirments
      run: |
        sudo apt install build-essential flex bison libssl-dev libelf-dev qt5-default pkg-config libncurses-dev -y
        git clone https://github.com/microsoft/WSL2-Linux-Kernel.git -b linux-msft-wsl-4.19.y
        cd WSL2-Linux-Kernel
        curl https://gist.githubusercontent.com/Bartixxx32/f8486d049b5d298ec43e018ca1e24e40/raw/9740939420339a35b2fdc4c06186255c2e69901b/kernel-config >> .config
    - name: Build
      run: make
      
      
        
